packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.0
  "@trpc/client": ^11.0.0-rc.528
  "@trpc/react-query": ^11.0.0-rc.528
  "@trpc/server": ^11.0.0-rc.528
  eslint: ^9.12.0
  prettier: ^3.3.3
  superjson: ^2.2.1
  typescript: ^5.6.2
  zod: ^3.23.8

catalogs:
  dates:
    date-fns: ^4.1.0
    "@date-fns/tz": ^1.1.2
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0
  supabase:
    "@supabase/supabase-js": ^2.45.4
    "@supabase/ssr": ^0.5.1
  tailwind:
    tailwindcss: ^3.4.13
    tailwindcss-animate: ^1.0.7
