// This file is auto-generated by @hey-api/openapi-ts

export const HealthCheckResponseSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
    user_id: {
      type: "string",
      title: "User Id",
    },
    created_at: {
      type: "string",
      title: "Created At",
    },
    message: {
      type: "string",
      title: "Message",
    },
    batches_processed: {
      type: "integer",
      title: "Batches Processed",
    },
    title: {
      type: "string",
      title: "Title",
    },
    content: {
      type: "string",
      title: "Content",
    },
    transcript: {
      type: "string",
      title: "Transcript",
    },
  },
  type: "object",
  required: [
    "id",
    "user_id",
    "created_at",
    "message",
    "batches_processed",
    "title",
    "content",
    "transcript",
  ],
  title: "HealthCheckResponse",
} as const;

export const UnauthorizedErrorResponseSchema = {
  properties: {
    detail: {
      type: "string",
      title: "Detail",
    },
  },
  type: "object",
  required: ["detail"],
  title: "UnauthorizedErrorResponse",
} as const;
