// This file is auto-generated by @hey-api/openapi-ts

export const ConformationalBPredictionSchema = {
  properties: {
    job_id: {
      type: "string",
      title: "Job Id",
    },
    id: {
      type: "string",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
    pdb_id: {
      type: "string",
      title: "Pdb Id",
    },
    chain: {
      type: "string",
      title: "Chain",
    },
    bcr_recognition_probability_method: {
      type: "string",
      title: "Bcr Recognition Probability Method",
    },
    surface_accessibility_method: {
      type: "string",
      title: "Surface Accessibility Method",
    },
    result: {
      items: {
        $ref: "#/components/schemas/PredictionResult",
      },
      type: "array",
      title: "Result",
    },
    csv_download_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Csv Download Url",
    },
  },
  type: "object",
  required: [
    "job_id",
    "id",
    "created_at",
    "updated_at",
    "pdb_id",
    "chain",
    "bcr_recognition_probability_method",
    "surface_accessibility_method",
    "result",
    "csv_download_url",
  ],
  title: "ConformationalBPrediction",
} as const;

export const ConformationalBPredictionCreateSchema = {
  properties: {
    job_id: {
      type: "string",
      title: "Job Id",
    },
    pdb_id: {
      type: "string",
      maxLength: 10,
      title: "Pdb Id",
    },
    chain: {
      type: "string",
      maxLength: 10,
      title: "Chain",
    },
    bcr_recognition_probability_method: {
      type: "string",
      maxLength: 50,
      title: "Bcr Recognition Probability Method",
    },
    surface_accessibility_method: {
      type: "string",
      maxLength: 50,
      title: "Surface Accessibility Method",
    },
    result: {
      items: {
        $ref: "#/components/schemas/PredictionResult",
      },
      type: "array",
      title: "Result",
      default: [],
    },
  },
  type: "object",
  required: [
    "job_id",
    "pdb_id",
    "chain",
    "bcr_recognition_probability_method",
    "surface_accessibility_method",
  ],
  title: "ConformationalBPredictionCreate",
} as const;

export const ConformationalBPredictionUpdateSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
    result: {
      items: {
        $ref: "#/components/schemas/PredictionResult",
      },
      type: "array",
      title: "Result",
    },
  },
  type: "object",
  required: ["id", "result"],
  title: "ConformationalBPredictionUpdate",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthCheckResponseSchema = {
  properties: {
    message: {
      type: "string",
      title: "Message",
    },
    batches_processed: {
      type: "integer",
      title: "Batches Processed",
    },
    title: {
      type: "string",
      title: "Title",
    },
    content: {
      type: "string",
      title: "Content",
    },
    transcript: {
      type: "string",
      title: "Transcript",
    },
  },
  type: "object",
  required: ["message", "batches_processed", "title", "content", "transcript"],
  title: "HealthCheckResponse",
} as const;

export const JobSchema = {
  properties: {
    profile_id: {
      type: "string",
      title: "Profile Id",
    },
    id: {
      type: "string",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
    name: {
      type: "string",
      title: "Name",
    },
    type: {
      $ref: "#/components/schemas/JobType",
    },
    status: {
      $ref: "#/components/schemas/JobStatus",
    },
    share_token: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Share Token",
    },
    conformational_b_predictions: {
      items: {
        $ref: "#/components/schemas/ConformationalBPrediction",
      },
      type: "array",
      title: "Conformational B Predictions",
      default: [],
    },
  },
  type: "object",
  required: [
    "profile_id",
    "id",
    "created_at",
    "updated_at",
    "name",
    "type",
    "status",
    "share_token",
  ],
  title: "Job",
} as const;

export const JobCreateSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 256,
      title: "Name",
    },
    type: {
      $ref: "#/components/schemas/JobType",
    },
  },
  type: "object",
  required: ["name", "type"],
  title: "JobCreate",
} as const;

export const JobStatusSchema = {
  type: "string",
  enum: ["pending", "running", "completed", "failed"],
  title: "JobStatus",
} as const;

export const JobTypeSchema = {
  type: "string",
  enum: ["linear-b", "conformational-b", "mhc-i", "mhc-ii"],
  title: "JobType",
} as const;

export const JobUpdateSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 256,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    type: {
      anyOf: [
        {
          $ref: "#/components/schemas/JobType",
        },
        {
          type: "null",
        },
      ],
    },
    share_token: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Share Token",
    },
  },
  type: "object",
  required: ["id"],
  title: "JobUpdate",
} as const;

export const PredictionResultSchema = {
  properties: {
    PDB_ID: {
      type: "string",
      title: "Pdb Id",
    },
    Chain: {
      type: "string",
      title: "Chain",
    },
    Residue_position: {
      type: "integer",
      title: "Residue Position",
    },
    AA: {
      type: "string",
      title: "Aa",
    },
    Epitope_score: {
      type: "number",
      title: "Epitope Score",
    },
    N_glyco_label: {
      type: "integer",
      title: "N Glyco Label",
    },
  },
  type: "object",
  required: [
    "PDB_ID",
    "Chain",
    "Residue_position",
    "AA",
    "Epitope_score",
    "N_glyco_label",
  ],
  title: "PredictionResult",
} as const;

export const UnauthorizedErrorResponseSchema = {
  properties: {
    detail: {
      type: "string",
      title: "Detail",
    },
  },
  type: "object",
  required: ["detail"],
  title: "UnauthorizedErrorResponse",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
