import type { Options } from "@hey-api/client-fetch";
import { createClient, createConfig } from "@hey-api/client-fetch";

import type { HealthCheckError, HealthCheckResponse2 } from "./types.gen";

// This file is auto-generated by @hey-api/openapi-ts

export const client = createClient(createConfig());

/**
 * Check
 * Secured health check endpoint.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckResponse2,
    HealthCheckError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/health",
  });
};
