import type { Options } from "@hey-api/client-fetch";
import { createClient, createConfig } from "@hey-api/client-fetch";

import type {
  ConformationalBpredictionCreateConformationalBpredictionData,
  ConformationalBpredictionCreateConformationalBpredictionError,
  ConformationalBpredictionCreateConformationalBpredictionResponse,
  ConformationalBpredictionDeleteConformationalBpredictionData,
  ConformationalBpredictionDeleteConformationalBpredictionError,
  ConformationalBpredictionDeleteConformationalBpredictionResponse,
  ConformationalBpredictionGetConformationalBpredictionData,
  ConformationalBpredictionGetConformationalBpredictionError,
  ConformationalBpredictionGetConformationalBpredictionResponse,
  ConformationalBpredictionUpdateConformationalBpredictionData,
  ConformationalBpredictionUpdateConformationalBpredictionError,
  ConformationalBpredictionUpdateConformationalBpredictionResponse,
  HealthCheckError,
  HealthCheckResponse2,
  JobCreateJobData,
  JobCreateJobError,
  JobCreateJobResponse,
  JobDeleteJobData,
  JobDeleteJobError,
  JobDeleteJobResponse,
  JobGetJobData,
  JobGetJobError,
  JobGetJobResponse,
  JobGetUserJobsError,
  JobGetUserJobsResponse,
  JobUpdateJobData,
  JobUpdateJobError,
  JobUpdateJobResponse,
} from "./types.gen";
import {
  ConformationalBpredictionCreateConformationalBpredictionResponseTransformer,
  ConformationalBpredictionDeleteConformationalBpredictionResponseTransformer,
  ConformationalBpredictionGetConformationalBpredictionResponseTransformer,
  ConformationalBpredictionUpdateConformationalBpredictionResponseTransformer,
  JobCreateJobResponseTransformer,
  JobDeleteJobResponseTransformer,
  JobGetJobResponseTransformer,
  JobGetUserJobsResponseTransformer,
  JobUpdateJobResponseTransformer,
} from "./types.gen";

// This file is auto-generated by @hey-api/openapi-ts

export const client = createClient(createConfig());

/**
 * Check
 * Secured health check endpoint.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckResponse2,
    HealthCheckError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/health",
  });
};

/**
 * Get User Jobs
 */
export const jobGetUserJobs = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    JobGetUserJobsResponse,
    JobGetUserJobsError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/job/",
    responseTransformer: JobGetUserJobsResponseTransformer,
  });
};

/**
 * Create Job
 */
export const jobCreateJob = <ThrowOnError extends boolean = false>(
  options: Options<JobCreateJobData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    JobCreateJobResponse,
    JobCreateJobError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/job/",
    responseTransformer: JobCreateJobResponseTransformer,
  });
};

/**
 * Update Job
 */
export const jobUpdateJob = <ThrowOnError extends boolean = false>(
  options: Options<JobUpdateJobData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<
    JobUpdateJobResponse,
    JobUpdateJobError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/job/{id}",
    responseTransformer: JobUpdateJobResponseTransformer,
  });
};

/**
 * Get Job
 */
export const jobGetJob = <ThrowOnError extends boolean = false>(
  options: Options<JobGetJobData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    JobGetJobResponse,
    JobGetJobError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/job/{id}",
    responseTransformer: JobGetJobResponseTransformer,
  });
};

/**
 * Delete Job
 */
export const jobDeleteJob = <ThrowOnError extends boolean = false>(
  options: Options<JobDeleteJobData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    JobDeleteJobResponse,
    JobDeleteJobError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/job/{id}",
    responseTransformer: JobDeleteJobResponseTransformer,
  });
};

/**
 * Create Conformational B Prediction
 */
export const conformationalBPredictionCreateConformationalBPrediction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConformationalBpredictionCreateConformationalBpredictionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).post<
    ConformationalBpredictionCreateConformationalBpredictionResponse,
    ConformationalBpredictionCreateConformationalBpredictionError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/conformationalBPrediction/",
    responseTransformer:
      ConformationalBpredictionCreateConformationalBpredictionResponseTransformer,
  });
};

/**
 * Get Conformational B Prediction
 */
export const conformationalBPredictionGetConformationalBPrediction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConformationalBpredictionGetConformationalBpredictionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ConformationalBpredictionGetConformationalBpredictionResponse,
    ConformationalBpredictionGetConformationalBpredictionError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/conformationalBPrediction/{id}",
    responseTransformer:
      ConformationalBpredictionGetConformationalBpredictionResponseTransformer,
  });
};

/**
 * Update Conformational B Prediction
 */
export const conformationalBPredictionUpdateConformationalBPrediction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConformationalBpredictionUpdateConformationalBpredictionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).put<
    ConformationalBpredictionUpdateConformationalBpredictionResponse,
    ConformationalBpredictionUpdateConformationalBpredictionError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/conformationalBPrediction/{id}",
    responseTransformer:
      ConformationalBpredictionUpdateConformationalBpredictionResponseTransformer,
  });
};

/**
 * Delete Conformational B Prediction
 */
export const conformationalBPredictionDeleteConformationalBPrediction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConformationalBpredictionDeleteConformationalBpredictionData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).delete<
    ConformationalBpredictionDeleteConformationalBpredictionResponse,
    ConformationalBpredictionDeleteConformationalBpredictionError,
    ThrowOnError
  >({
    ...options,
    url: "/api/v1/conformationalBPrediction/{id}",
    responseTransformer:
      ConformationalBpredictionDeleteConformationalBpredictionResponseTransformer,
  });
};
