// This file is auto-generated by @hey-api/openapi-ts

export type ClassificationResult = {
  label: string;
  score: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type HealthCheckResponse = {
  message: string;
  batches_processed: number;
  title: string;
  content: string;
  transcript: string;
};

export type PredictRequest = {
  inputs: string;
};

export type PredictionResponse = {
  results: Array<ClassificationResult>;
};

export type UnauthorizedErrorResponse = {
  detail: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type HealthCheckResponse2 = HealthCheckResponse;

export type HealthCheckError = UnauthorizedErrorResponse | unknown;

export type HfPredictData = {
  body: PredictRequest;
};

export type HfPredictResponse = PredictionResponse;

export type HfPredictError = unknown | HTTPValidationError;
